{% set name = "django-widget-tweaks" %}
{% set version = "1.4.11" %}
{% set sha256 = "07674e32031eda81077f0b8e390ce78d1d415e700cedd0396ef0ce452e95b94d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django

test:
  imports:
    - widget_tweaks

about:
  home: https://github.com/jazzband/django-widget-tweaks
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tweak the form field rendering in templates, not in python-level form definitions.

extra:
  recipe-maintainers:
    - scopatz
